name: 'Testmerge Conflict Detection'

on:
  push:
    branches:
      - testmerge
  pull_request_target:
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v3.0.2
        with:
          dirtyLabel: 'Testmerge Conflict'
          repoToken: ${{ secrets.GITHUB_TOKEN }}
